---
- name: Manage databases
  hosts: sqlservers
  gather_facts: false
  tasks:
  - name: Set up PowerShell for fetching modules
    tags: prereqs
    ansible.builtin.win_shell: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module PowerShellGet -AllowClobber -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

  - name: Install SqlDatabase PsModule
    community.windows.win_psmodule:
      name: SqlServerDsc
      state: present
      allow_clobber: true

  - name: Manage databases
    ansible.windows.win_dsc:
      resource_name: SqlDatabase
      ServerName: "{{ sql_server_name | default('winthrop') }}"
      Name: "{{ sql_server_db | default('my-new-db') }}"
      Ensure: "{{ sql_server_db_state | default('Present') }}"
      InstanceName: "{{ sql_instance_name | default('MSSQLSERVER') }}"


