---
- name: Manage databases
  hosts: sqlservers
  gather_facts: false
  vars:
    sql_server_db_state: 'Present'
    sql_server_db: 'my-new-db'
    sql_instance_name: ""
    sql_server_name: "winthrop"
  tasks:
#  - name: Install SqlServer PsModule
#    community.windows.win_psmodule:
#      name: SqlServer
#      state: present
#      allow_clobber: true

  - name: Manage databases
    ansible.windows.win_dsc:
      resource_name: SqlDatabase
      ServerName: "{{ sql_server_name }}"
      Name: "{{ sql_server_db }}"
      Ensure: "{{ sql_server_db_state }}"
      InstanceName: "{{ sql_instance_name }}"


