---
- name: Manage databases
  hosts: sqlservers
  vars:
    sql_server_db_state: 'Present'
    sql_server_db: 'my-new-db'
    sql_instance_name: ""
  tasks:
  - name: Install SqlServer PsModule
    community.windows.win_psmodule:
      name: SqlServer
      state: present
      allow_clobber: true

  - name: Manage databases
    ansible.windows.win_dsc:
      resource_name: SqlDatabase
      ServerName: "winthrop.ansible.local"
      Name: "{{ sql_server_db }}"
      Ensure: "{{ sql_server_db_state }}"
      InstanceName: sql_instance_name


