---
- name: Manage databases
  hosts: dc01.ansible.local
  gather_facts: false
  vars:
    sql_server_db_state: 'Present'
    sql_server_db: 'my-new-db'
    sql_instance_name: "winthrop"
    sql_server_name: "winthrop"
  tasks:
  - name: Set up PowerShell for fetching modules
    tags: prereqs
    ansible.builtin.win_shell: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module PowerShellGet -AllowClobber -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

  - name: Install SqlDatabase PsModule
    community.windows.win_psmodule:
      name: SqlDatabase
      state: present
      allow_clobber: true

  - name: Manage databases
    ansible.windows.win_dsc:
      resource_name: SqlDatabase
      ServerName: "{{ sql_server_name }}"
      Name: "{{ sql_server_db }}"
      Ensure: "{{ sql_server_db_state }}"
      InstanceName: "{{ sql_instance_name }}"


