---
- name: Set a password
  hosts: dc01.ansible.local
  gather_facts: false
  tasks:
  - name: Set a user's password 
    microsoft.ad.user:
      identity: "{{ set_password_user }}"
      firstname: "{{ set_password_user }}"
      surname: "{{ set_password_user }}"
      name: "{{ set_password_user }}"
      password: "{{ set_password_password }}"
      state: present
      domain_server: dc01.ansible.local

