---
- name: Set a password
  hosts: dc01.ansible.local
  tasks:
  - name: Set a user's password 
    microsoft.ad.user:
      identity: "{{ set_password_user }}"
      name: "{{ set_password_user }}"
      password: "{{ set_password_password }}"
      state: present
      path: "ou=Users,dc=ansible,dn=local"

