download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/brianaddicks-mssql_tools-1.0.0.tar.gz
format_version: 1.0.0
name: mssql_tools
namespace: brianaddicks
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/brianaddicks/mssql_tools/versions/1.0.0/
